package:
  name: imbalanced-learn
  version: "0.4.0"

source:
  git_rev: 0.4.0
  git_url: https://github.com/scikit-learn-contrib/imbalanced-learn.git

build:
  number: 0
  noarch: python

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - scikit-learn 0.19.*

test:
  requires:
    - pytest
    - pytest-cov
  imports:
    - imblearn

about:
  home: https://github.com/scikit-learn-contrib/imbalanced-learn
  license: MIT
  license_file: LICENSE

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
