package:
  name: imbalanced-learn
  version: "0.3.0"

source:
  git_rev: 0.3.0
  git_url: https://github.com/scikit-learn-contrib/imbalanced-learn.git

requirements:
  build:
    - python
    - setuptools
    - numpy 1.13.*
    - scipy 0.19.*
    - scikit-learn 0.19.*
  run:
    - python
    - numpy 1.13.*
    - scipy 0.19.*
    - scikit-learn 0.19.*

test:
  requires:
    - nose
    - coverage
    - pytest
    - pytest-cov
  imports:
    - imblearn

about:
  home: https://github.com/scikit-learn-contrib/imbalanced-learn
  license: MIT
  license_file: LICENSE

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
